### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#420]
A long time has passed since last release. 1.5.0 will have a few minor changes and quality changes.

- [Customize button color](https://github.com/matterpoll/matterpoll/issues/267)
- [Allow a user to remove a cast vote](https://github.com/matterpoll/matterpoll/issues/379)

Before we release, the translations have to be updated.

The current process is:

- [x] France: @ldidry (#426)
- [x] German: @vorlif @hanzei (#432)
- [x] Japanese: @kaakaa (#421)
- [ ] Korean: @potatogim
- [ ] Polish: @burasuk
- [x] Russian: @ChiefAbbot (#428)
- [x] Simplified Chinese: @sharuru (#423)
- [x] Spanish: @ernestoittig (#424)
- [x] Traditional Chinese: @mouson (#425)

Please submit your translation, so we can release this soon. You can find the process for this [here](https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md#translation-process-for-existing-languages).

**Comment by kaakaa** [comment]
I'll cut new release in few days.

**Comment by kaakaa** [comment]
Shipped new release v1.5.0. Thanks for all contributors to v1.5.0.
https://github.com/matterpoll/matterpoll/releases/tag/v1.5.0

And start the process for updating community plugin in the Marketplace.
https://github.com/mattermost/mattermost-marketplace/issues/298

**Comment by nderambure** [comment]
Thanks ;)
