### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by kaakaa** [matterpoll/matterpoll#476]
1.6.0 will have a cool feature to show progress in RHS, some bug fixes, and some dev updates.

* Enhancement
  * #431
* Bug fixes
  * #440
  * #443
  * #469
* Updates for dev
  * #438
  * #443
  * #453

Before we release, the traslations have to be updated.

The current process is:

- [x] France: @ldidry (#481)
- [x] German: @vorlif @hanzei (#483)
- [x] Japanese: @kaakaa (#477)
- [ ] Korean: @potatogim
- [ ] Polish: @burasuk
- [ ] Russian: @ChiefAbbot
- [x] Simplified Chinese: @sharuru (#478)
- [x] Spanish: @ernestoittig (#482)
- [x] Traditional Chinese: @mouson (#480)

Please submit your translation, so we can release this soon. You can find the process for this [here](https://github.com/matterpoll/matterpoll/blob/master/CONTRIBUTING.md#translation-process-for-existing-languages).

**Comment by kaakaa** [comment]
I'll cut new release in a few days. I'm welcoming contributions to localization that still be unfinished. If needing more time, let me know it.

**Comment by q-wertz** [comment]
Tried my best, hope this helps :)

**Comment by kaakaa** [comment]
Cut and release new version [Release v1\.6\.0 · matterpoll/matterpoll](https://github.com/matterpoll/matterpoll/releases/tag/v1.6.0), and the process to release v1.6.0 to marketplace is kicked off [here](https://github.com/mattermost/mattermost-marketplace/issues/367).

Thanks for your all contributions ❤️
